#!/bin/bash

#
# Copyright © 2013 Max Ruman
#
# This file is part of Wok.
#
# Wok is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# Wok is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Wok. If not, see <http://www.gnu.org/licenses/>.
#

E_INVALID_USAGE=1
E_TEST_FAILED=2

if [[ -n $1 ]]; then
	inc="$1"
else
	inc="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)/src/common/ui_confirm.bash"
fi

if [[ ! -f $inc ]]; then
	echo "Source file ${inc} does not exist" >&2
	exit $E_INVALID_USAGE
fi

. "$inc"

bin="ui_confirm"

assert_true()
{
	local descr="$1"
	local resp="$2"

	echo -n "Testing ${descr}: "
	if echo -e "$resp" | "$bin" >/dev/null 2>/dev/null; then
		echo "OK"
	else
		echo -e "\033[0;31mfailed!\033[0m"
		exit $E_TEST_FAILED
	fi
}

assert_false()
{
	local descr="$1"
	local resp="$2"

	echo -n "Testing ${descr}: "
	if ! echo -e "$resp" | "$bin" >/dev/null 2>/dev/null; then
		echo "OK"
	else
		echo -e "\033[0;31mfailed!\033[0m"
		exit $E_TEST_FAILED
	fi
}

assert_true  "confirmation (lowercase)" "y"
assert_true  "confirmation (uppercase)" "Y"
assert_true  "confirmation (phrase)"    "yes, why not\!"
assert_true  "confirmation (repeat)"    "invalid\nyes"
assert_false "repeal (lowercase)"       "n"
assert_false "repeal (uppercase)"       "N"
assert_false "repeal (phrase)"          "no, thanks."
assert_false "repeal (repeat)"          "invalid\nno"
