#!/bin/bash

#
# Copyright © 2013 Max Ruman
#
# This file is part of Wok.
#
# Wok is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# Wok is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Wok. If not, see <http://www.gnu.org/licenses/>.
#

E_INVALID_USAGE=1
E_TEST_FAILED=2
E_SYSTEM_ERROR=3

if [[ -n "$1" ]]; then
	bin="$1"
else
	bin="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)/dist/wok/util/ini_get"
fi

if [[ ! -x "$bin" ]]; then
	echo "Target ${bin} does not exist or is not executable" >&2
	exit $E_INVALID_USAGE
fi

ini_file=

ini_init()
{
	local contents=("$@")

	if ! ini_file="$(mktemp)"; then
		echo "Could not create a temporary file" >&2
		exit $E_SYSTEM_ERROR
	fi
	echo -e "${contents[@]}" >"$ini_file"
}

ini_clean()
{
	rm "$ini_file"
}

test_fail()
{
	echo -e "\033[0;31mfailed!\033[0m"
	ini_clean
	exit $E_TEST_FAILED
}

assert_fails()
{
	local descr="$1"
	local ini_sect="$2"
	local ini_key="$3"

	echo -n "Testing ${descr}: "
	if ! "$bin" "$ini_file" "$ini_sect" "$ini_key" >/dev/null 2>/dev/null; then
		echo "OK"
	else
		test_fail
	fi
}

assert_equals()
{
	local descr="$1"
	local expect="$(echo -e "$2")"
	local ini_sect="$3"
	local ini_key="$4"

	echo -n "Testing ${descr}: "
	if result="$("$bin" "$ini_file" "$ini_sect" "$ini_key" 2>/dev/null)" && [[ $result == $expect ]]; then
		echo "OK"
	else
		test_fail
	fi
}

ini_init "
	[wok]

	version = 1.0.0
	author  = Max Ruman

	[wok_www]

	path     = /srv/www
	template = /srv/www/.template
	vhost[]  = example.org
	vhost[]  = example.com
"

assert_equals "string read #1" "1.0.0" "wok" "version"
assert_equals "string read #2"    "Max Ruman" "wok" "author"
assert_equals "array read"    "example.org\nexample.com" "wok_www" "vhost"
assert_fails  "invalid usage #1"
assert_fails  "invalid usage #1" "wok"
assert_fails  "invalid key" "wok" "invalid_key"
assert_fails  "invalid section" "invalid_section" "version"
assert_fails  "direct key access" "" "version"

ini_clean
