#!/bin/bash

#
# Copyright © 2013-2015 Max Ruman <rmx@guanako.be>
#
# This file is part of Wok.
#
# Wok is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# Wok is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Wok. If not, see <http://www.gnu.org/licenses/>.
#

E_INVALID_USAGE=1
E_TEST_FAILED=2

if [[ -n $1 ]]; then
	inc="$1"
else
	inc="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)/src/common/array.bash"
fi

if [[ ! -f $inc ]]; then
	echo "Source file ${inc} does not exist" >&2
	exit $E_INVALID_USAGE
fi

. "$inc"

bin="array_has"

test_fail()
{
	echo -e "\033[0;31mfailed!\033[0m"
	exit $E_TEST_FAILED
}

assert_true()
{
	local descr="$1"
	shift

	echo -n "Testing ${descr}: "
	if "$bin" "$@" >/dev/null 2>/dev/null; then
		echo "OK"
	else
		test_fail
	fi
}

assert_false()
{
	local descr="$1"
	shift

	echo -n "Testing ${descr}: "
	if ! "$bin" "$@" >/dev/null 2>/dev/null; then
		echo "OK"
	else
		test_fail
	fi
}

list=("hello world" "john is here" "adriatic" "seq" "on the top")

assert_true  "existing value #1"    list "adriatic"
assert_true  "existing value #2"    list "john is here"
assert_false "unavailable value #1" list "unavailable"
assert_false "unavailable value #2" list "adriatic seq"
