#!/bin/bash

#
# Copyright © 2013-2015 Max Ruman <rmx@guanako.be>
#
# This file is part of Wok.
#
# Wok is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
#
# Wok is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Wok. If not, see <http://www.gnu.org/licenses/>.
#

E_INVALID_USAGE=1
E_TEST_FAILED=2

if [[ -n $1 ]]; then
	inc="$1"
else
	inc="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)/src/common/array.bash"
fi

if [[ ! -f $inc ]]; then
	echo "Source file ${inc} does not exist" >&2
	exit $E_INVALID_USAGE
fi

. "$inc"

bin="array_reverse"

test_descr()
{
	local descr="$1"

	echo -n "Testing ${descr}..."
}

test_fail()
{
	echo -e "\033[0;31mfailed!\033[0m"
	exit $E_TEST_FAILED
}

test_succeed()
{
	echo "OK"
}

test_qexec()
{
	"$bin" "$@" >/dev/null 2>/dev/null
}

{
	list=("hello world" "john is here" "adriatic")
	test_descr "list reversing"
	test_qexec list || test_fail
	[[ ${#list[@]} -ne 3 ]] && test_fail
	[[ ${list[0]} != "adriatic" ]] && test_fail
	[[ ${list[1]} != "john is here" ]] && test_fail
	[[ ${list[2]} != "hello world" ]] && test_fail
	test_succeed
}
